version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: php artisan serve --host=0.0.0.0 --port=8000

    db:
        # kuganti versi 15 -> 12
        image: postgres:12
        container_name: pg_db
        restart: always
        environment:
            POSTGRES_DB: task_manager
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret123
        ports:
            - "5432:5432"
